services:
  - type: web
    name: storychain-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node test-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
